# Generated by Django 5.2 on 2025-04-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=120)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('adres', models.TextField(blank=True)),
                ('firmasi', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_tipi', models.CharField(help_text='Örn: Piston kolu, şaft vb.', max_length=200)),
                ('adet', models.PositiveIntegerField(default=1, help_text='Sipariş adedi')),
                ('iscilik_turu', models.CharField(choices=[('taslama', 'Silindirik Piston Taşlama'), ('krom_kaplama', 'Sert Krom Kaplama')], max_length=50)),
                ('tarih', models.DateField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı')], default='beklemede', max_length=20)),
                ('aciklama', models.TextField(blank=True, help_text='Ekstra bilgiler ve ölçüler (ölçü, çap, uzunluk vb.)')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siparis.musteri')),
            ],
        ),
    ]
