# Generated by Django 5.2 on 2025-04-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0002_musteri_kayit_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('stok_miktari', models.PositiveIntegerField(default=0)),
                ('birim', models.CharField(default='adet', max_length=20)),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('gunluk', 'Günlük Rapor'), ('haftalik', 'Haftalık Rapor'), ('aylik', 'Aylık Rapor')], max_length=20)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('toplam_siparis', models.IntegerField(default=0)),
                ('toplam_gelir', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='siparis',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Birim fiyat (TL)', max_digits=10),
        ),
        migrations.AddField(
            model_name='siparis',
            name='odeme_durumu',
            field=models.CharField(choices=[('odenmedi', 'Ödenmedi'), ('kismi_odendi', 'Kısmen Ödendi'), ('odendi', 'Ödendi')], default='odenmedi', max_length=20),
        ),
        migrations.AddField(
            model_name='siparis',
            name='odenen_miktar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ödenen miktar (TL)', max_digits=10),
        ),
        migrations.AddField(
            model_name='siparis',
            name='oncelik',
            field=models.PositiveSmallIntegerField(default=0, help_text='Yüksek değerler daha öncelikli'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslim_tarihi',
            field=models.DateField(blank=True, help_text='Siparişin teslim edildiği tarih', null=True),
        ),
        migrations.AddField(
            model_name='siparis',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Toplam fiyat (TL)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı'), ('teslim_edildi', 'Teslim Edildi'), ('iptal_edildi', 'İptal Edildi')], default='beklemede', max_length=20),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='iscilik_turu',
            field=models.CharField(choices=[('taslama', 'Silindirik Piston Taşlama'), ('krom_kaplama', 'Sert Krom Kaplama'), ('honlama', 'Honlama'), ('polisaj', 'Polisaj'), ('diger', 'Diğer İşlemler')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='siparis.musteri'),
        ),
        migrations.CreateModel(
            name='MalzemeKullanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kullanim_kayitlari', to='siparis.malzeme')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanilan_malzemeler', to='siparis.siparis')),
            ],
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='siparis.siparis')),
            ],
        ),
    ]
