# Generated by Django 5.2 on 2025-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0003_malzeme_rapor_siparis_birim_fiyat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malzeme',
            options={'verbose_name': 'Malzeme', 'verbose_name_plural': 'Malzemeler'},
        ),
        migrations.AlterModelOptions(
            name='malzemekullanimi',
            options={'verbose_name': 'Malzeme Kullanımı', 'verbose_name_plural': 'Malzeme Kullanımları'},
        ),
        migrations.AlterModelOptions(
            name='musteri',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='odeme',
            options={'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.AlterModelOptions(
            name='rapor',
            options={'verbose_name': 'Rapor', 'verbose_name_plural': 'Raporlar'},
        ),
        migrations.AlterModelOptions(
            name='siparis',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AddField(
            model_name='malzeme',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Malzeme hakkında detaylı bilgi'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='tur',
            field=models.CharField(choices=[('celik', 'Çelik'), ('aluminyum', 'Alüminyum'), ('paslanmaz', 'Paslanmaz Çelik'), ('bronz', 'Bronz'), ('bakir', 'Bakır'), ('plastik', 'Plastik'), ('kaucuk', 'Kauçuk'), ('krom', 'Krom'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Malzeme Türü'),
        ),
    ]
