# Generated by Django 5.2.3 on 2025-06-10 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0004_alter_malzeme_options_alter_malzemekullanimi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malzeme',
            options={'ordering': ['ad'], 'verbose_name': 'Malzeme', 'verbose_name_plural': 'Malzemeler'},
        ),
        migrations.AlterModelOptions(
            name='malzemekullanimi',
            options={'ordering': ['-tarih'], 'verbose_name': 'Malzeme Kullanımı', 'verbose_name_plural': 'Malzeme Kullanımları'},
        ),
        migrations.AlterModelOptions(
            name='musteri',
            options={'ordering': ['-kayit_tarihi', 'isim'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='odeme',
            options={'ordering': ['-tarih'], 'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.AlterModelOptions(
            name='rapor',
            options={'ordering': ['-olusturulma_tarihi'], 'verbose_name': 'Rapor', 'verbose_name_plural': 'Raporlar'},
        ),
        migrations.AlterModelOptions(
            name='siparis',
            options={'ordering': ['-oncelik', '-tarih'], 'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AddField(
            model_name='malzeme',
            name='minimum_stok',
            field=models.PositiveIntegerField(default=5, help_text='Uyarı verilecek minimum stok seviyesi'),
        ),
        migrations.AddField(
            model_name='malzemekullanimi',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Kullanım hakkında ek bilgiler', max_length=255),
        ),
        migrations.AddField(
            model_name='rapor',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Rapor hakkında ek bilgiler'),
        ),
        migrations.AddField(
            model_name='rapor',
            name='toplam_odenen',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rapor dönemindeki toplam tahsil edilen miktar (TL)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='ad',
            field=models.CharField(help_text='Malzemenin adı', max_length=100),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='birim',
            field=models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kilogram'), ('gr', 'Gram'), ('lt', 'Litre'), ('mt', 'Metre'), ('cm', 'Santimetre'), ('m2', 'Metrekare'), ('m3', 'Metreküp'), ('paket', 'Paket'), ('kutu', 'Kutu')], default='adet', help_text='Stok miktarı birimi (adet, kg, lt vb.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Birim başına fiyat (TL)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='son_guncelleme',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='stok_miktari',
            field=models.PositiveIntegerField(default=0, help_text='Mevcut stok miktarı'),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='tur',
            field=models.CharField(choices=[('celik', 'Çelik'), ('aluminyum', 'Alüminyum'), ('paslanmaz', 'Paslanmaz Çelik'), ('bronz', 'Bronz'), ('bakir', 'Bakır'), ('plastik', 'Plastik'), ('kaucuk', 'Kauçuk'), ('krom', 'Krom'), ('diger', 'Diğer')], default='diger', help_text='Malzemenin türü/kategorisi', max_length=20, verbose_name='Malzeme Türü'),
        ),
        migrations.AlterField(
            model_name='malzemekullanimi',
            name='malzeme',
            field=models.ForeignKey(help_text='Kullanılan malzeme', on_delete=django.db.models.deletion.PROTECT, related_name='kullanim_kayitlari', to='siparis.malzeme'),
        ),
        migrations.AlterField(
            model_name='malzemekullanimi',
            name='miktar',
            field=models.PositiveIntegerField(help_text='Kullanılan miktar'),
        ),
        migrations.AlterField(
            model_name='malzemekullanimi',
            name='siparis',
            field=models.ForeignKey(help_text='Malzemenin kullanıldığı sipariş', on_delete=django.db.models.deletion.CASCADE, related_name='kullanilan_malzemeler', to='siparis.siparis'),
        ),
        migrations.AlterField(
            model_name='malzemekullanimi',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, help_text='Kullanım kaydının oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='adres',
            field=models.TextField(blank=True, help_text='Müşteri adresi'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='firmasi',
            field=models.CharField(blank=True, help_text='Müşterinin çalıştığı firma', max_length=150),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='isim',
            field=models.CharField(help_text='Müşteri adı ve soyadı', max_length=120),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='telefon',
            field=models.CharField(blank=True, help_text='İletişim telefon numarası', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Ödeme hakkında ek bilgiler (ödeme yöntemi, makbuz no vb.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='miktar',
            field=models.DecimalField(decimal_places=2, help_text='Ödeme miktarı (TL)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='siparis',
            field=models.ForeignKey(help_text='Ödemenin yapıldığı sipariş', on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='siparis.siparis'),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, help_text='Ödemenin yapıldığı tarih ve saat'),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='baslangic_tarihi',
            field=models.DateField(help_text='Rapor dönemi başlangıç tarihi'),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='baslik',
            field=models.CharField(help_text='Raporun başlığı', max_length=100),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='bitis_tarihi',
            field=models.DateField(help_text='Rapor dönemi bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, help_text='Raporun oluşturulma tarihi ve saati'),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='tip',
            field=models.CharField(choices=[('gunluk', 'Günlük Rapor'), ('haftalik', 'Haftalık Rapor'), ('aylik', 'Aylık Rapor'), ('ozel', 'Özel Rapor'), ('yillik', 'Yıllık Rapor')], help_text='Raporun tipi', max_length=20),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='toplam_gelir',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rapor dönemindeki toplam gelir (TL)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='toplam_siparis',
            field=models.IntegerField(default=0, help_text='Rapor dönemindeki toplam sipariş sayısı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı'), ('teslim_edildi', 'Teslim Edildi'), ('iptal_edildi', 'İptal Edildi')], default='beklemede', help_text='Siparişin mevcut durumu', max_length=20),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='iscilik_turu',
            field=models.CharField(choices=[('taslama', 'Silindirik Piston Taşlama'), ('krom_kaplama', 'Sert Krom Kaplama'), ('honlama', 'Honlama'), ('polisaj', 'Polisaj'), ('diger', 'Diğer İşlemler')], help_text='Yapılacak işçilik türü', max_length=50),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='musteri',
            field=models.ForeignKey(help_text='Siparişi veren müşteri', on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='siparis.musteri'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='odeme_durumu',
            field=models.CharField(choices=[('odenmedi', 'Ödenmedi'), ('kismi_odendi', 'Kısmen Ödendi'), ('odendi', 'Ödendi')], default='odenmedi', editable=False, help_text='Ödeme durumu', max_length=20),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='oncelik',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Yüksek'), (2, 'Acil')], default=0, help_text='Siparişin öncelik seviyesi'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='tarih',
            field=models.DateField(auto_now_add=True, help_text='Siparişin oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Toplam fiyat (TL)', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='malzemekullanimi',
            unique_together={('siparis', 'malzeme')},
        ),
    ]
